'use client';
import {site} from './config'; import {useEffect,useState} from 'react';
const Arrow=()=> <span aria-hidden>↗</span>;
export default function Page(){const [menu,setMenu]=useState(false); useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('seen')),{threshold:.12}); document.querySelectorAll('.reveal').forEach(e=>io.observe(e)); const cleanups:Array<()=>void>=[]; const media=window.matchMedia('(min-width: 761px)'); document.querySelectorAll<HTMLElement>('.areaGrid').forEach(track=>{const onWheel=(event:WheelEvent)=>{if(!media.matches||track.scrollWidth<=track.clientWidth+2||Math.abs(event.deltaY)<=Math.abs(event.deltaX))return; const max=track.scrollWidth-track.clientWidth; const movingRight=event.deltaY>0; const canMove=movingRight?track.scrollLeft<max-1:track.scrollLeft>1; if(!canMove)return; event.preventDefault(); track.scrollBy({left:event.deltaY,behavior:'auto'})}; track.addEventListener('wheel',onWheel,{passive:false}); cleanups.push(()=>track.removeEventListener('wheel',onWheel))}); return()=>{io.disconnect();cleanups.forEach(fn=>fn())}},[]); const wa=site.whatsapp?`https://wa.me/${site.whatsapp}?text=${encodeURIComponent('Olá! Gostaria de agendar uma conversa com '+site.name+'.')}`:site.map; const cta=site.whatsapp?'Fale com o escritório':'Ver contato no Google'; return <main className={`theme-${site.theme}`}>
 <header><a className="brand" href="#inicio"><b>{site.monogram}</b><span>{site.short}</span></a><button className="menu" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="nav" aria-label={menu?'Fechar menu':'Abrir menu'}>{menu?'Fechar':'Menu'}</button><nav id="nav" className={menu?'open':''} aria-label="Navegação principal"><a href="#atuacao" onClick={()=>setMenu(false)}>Atuação</a><a href="#escritorio" onClick={()=>setMenu(false)}>Escritório</a><a href="#contato" onClick={()=>setMenu(false)}>Contato</a><a className="navCta" href={wa}>Agendar <Arrow/></a></nav></header>
 <section className="hero" id="inicio"><img src={site.image} alt="Ambiente jurídico elegante"/><div className="veil"/><div className="heroCopy reveal"><small>{site.kicker}</small><h1>{site.title}</h1><p>{site.intro}</p><div className="actions"><a className="primary" href={wa}>{cta} <Arrow/></a><a className="textLink" href="#atuacao">Conheça a atuação ↓</a></div></div><div className="sideNote">PARAUAPEBAS · PARÁ</div><div className="scroll">Role para descobrir</div></section>
 <section className="manifest reveal"><span>01 · NOSSA VISÃO</span><blockquote>“{site.quote}”</blockquote></section>
 <section className="areas" id="atuacao"><div className="sectionHead reveal"><span>02 · ÁREAS DE ATUAÇÃO</span><h2>Direito explicado<br/>com clareza.</h2><p>Cada demanda começa com escuta atenta, análise responsável e orientação objetiva sobre os caminhos possíveis.</p></div><div className="areaGrid">{site.areas.map((a,i)=><article className="reveal" key={a[0]}><i>0{i+1}</i><h3>{a[0]}</h3><p>{a[1]}</p><Arrow/></article>)}</div></section>
 <section className="about" id="escritorio"><div className="aboutVisual reveal"><img src="/detail.jpg" alt="Detalhes de um ambiente de trabalho jurídico"/><div className="stamp">{site.monogram}<small>PARAUAPEBAS · PA</small></div></div><div className="aboutCopy reveal"><span>03 · O ESCRITÓRIO</span><h2>Presença quando<br/>mais importa.</h2><p>{site.about}</p><ul>{site.values.map(v=><li key={v}><b>✓</b>{v}</li>)}</ul><a className="textLink" href={wa}>Converse sobre seu caso <Arrow/></a></div></section>
 <section className="process"><div className="sectionHead reveal"><span>04 · COMO TRABALHAMOS</span><h2>Estratégia começa<br/>por entender.</h2></div><div className="steps"><article><b>01</b><h3>Escuta</h3><p>Compreensão do contexto, documentos e prioridades.</p></article><article><b>02</b><h3>Análise</h3><p>Leitura técnica e apresentação clara dos caminhos jurídicos.</p></article><article><b>03</b><h3>Condução</h3><p>Acompanhamento responsável e comunicação ao longo do trabalho.</p></article></div></section>
 <section className="contact" id="contato"><div className="contactTitle reveal"><small>05 · CONTATO</small><h2>Vamos conversar?</h2><p>Agende uma conversa inicial para apresentar sua demanda ao escritório.</p><a className="primary light" href={wa}>Abrir WhatsApp <Arrow/></a></div><div className="contactInfo reveal"><div><small>ENDEREÇO</small><p>{site.address}</p><a href={site.map}>Ver no Google Maps <Arrow/></a></div><div><small>TELEFONE</small><p>{site.phone}</p></div>{site.instagram&&<div><small>INSTAGRAM</small><a href={site.instagram}>Acessar perfil <Arrow/></a></div>}</div></section>
 <footer><div className="brand"><b>{site.monogram}</b><span>{site.short}</span></div><p>Conteúdo informativo. Cada situação jurídica exige análise individual.</p><span>© 2026 {site.short}</span></footer>{site.whatsapp&&<a className="whatsapp" href={wa} aria-label="Falar pelo WhatsApp">WhatsApp</a>}
 </main>}
